ALTER TABLE attendees ADD COLUMN IF NOT EXISTS ticket_type TEXT;
ALTER TABLE attendees ADD COLUMN IF NOT EXISTS meal_preference TEXT;
ALTER TABLE attendees ADD COLUMN IF NOT EXISTS reception BOOLEAN;

ALTER TABLE attendees ALTER COLUMN name DROP NOT NULL;
ALTER TABLE attendees ALTER COLUMN ticket_type DROP NOT NULL;
